In [17]:
import pandas as pd
import numpy as np
import os
import json

In [28]:
def read_results(results1):
    df1 = pd.DataFrame(results1).T
    new_df = pd.DataFrame()
    for i in df1.index:
        temp_df = pd.DataFrame.from_dict(df1.loc[i, 0] , orient='index', columns=['Value']).T
        new_df = pd.concat([new_df, temp_df], axis=0)
    new_df.index = df1.index
    new_df = pd.concat([df1, new_df], axis = 1)
    new_df = new_df.drop(columns=0)
    return new_df.round(4).loc[:,  ['test/cls/Acc', 'test/cls/Brier', 'test/cls/NLL','test/cal/ECE','test/cal/aECE']]

In [50]:
def read_results(results1):
    df1 = pd.DataFrame(results1).T
    new_df = pd.DataFrame()
    for i in df1.index:
        temp_df = pd.DataFrame.from_dict(df1.loc[i, 0] , orient='index', columns=['Value']).T
        new_df = pd.concat([new_df, temp_df], axis=0)
    new_df.index = df1.index
    new_df = pd.concat([df1, new_df], axis = 1)
    new_df = new_df.drop(columns=0)
    return new_df.round(4).loc[:,  ['test/cls/Brier']]

In [30]:
def format_latex_with_color(df1, df2):
    latex_str = ""
    # Ensure both DataFrames are the same size
    if df1.shape != df2.shape:
        raise ValueError("DataFrames must be of the same size")
    
    # Iterate through each row and column index
    l1 = ''
    l2 = ''
    for i in range(df1.shape[0]):
        row_str1 = "& "
        row_str2 = "& "
        for j in range(df1.shape[1]):
            val1 = df1.iloc[i, j]
            val2 = df2.iloc[i, j]
            # Apply color to the smaller value
            if val1 < val2:
                row_str1 += f"\\cellcolor{{gray!12}}{val1:.4f} & "
                row_str2 += f"{val2:.4f} & "
            elif val1 > val2:
                row_str1 += f"{val1:.4f} & "
                row_str2 += f"\\cellcolor{{gray!12}}{val2:.4f} & "
            else:  # values are equal, no color applied
                row_str1 += f"{val1:.4f} & "
                row_str2 += f"{val2:.4f} & "
        
        # Remove the last '&'
        row_str1 = '& ' + row_str1.strip('& ') + " \\\\\n"
        row_str2 = '& ' + row_str2.strip('& ') + " \\\\\n"
        # Add the rows to the main string
        l1 += row_str1
        l2 += row_str2
        latex_str += row_str1 + row_str2
    
    return l1 + l2

In [31]:
# with open('results_model_uq/results_single_deep_ensemble_v2.json') as f:
#     results11 = json.load(f)

# with open('results_model_uq/results_multi_task_deep_ensemble.json') as f:
#     results12 = json.load(f)

# with open('results_single_mc_dropout.json') as f:
#     results21 = json.load(f)

# with open('results_model_uq/results_multi_task_mc_dropout.json') as f:
#     results22 = json.load(f)

# with open('results_single_bnn.json') as f:
#     results31 = json.load(f)

# with open('results_single_bnn_2.json') as f:
#     results32 = json.load(f)

# with open('results_model_uq/results_multi_task_bnn.json') as f:
#     results33 = json.load(f)

In [32]:
with open('results_model_uq_v2/results_single_task_baseline.json') as f:
    results11 = json.load(f)

with open('results_model_uq_v2/results_single_task_deep_ensemble.json') as f:
    results12 = json.load(f)

with open('results_model_uq_v2/results_single_task_mc_dropout.json') as f:
    results13 = json.load(f)

In [33]:
with open('results_model_uq_v2/results_multi_task_baseline.json') as f:
    results21 = json.load(f)
    
with open('results_model_uq_v2/results_multi_task_deep_ensemble.json') as f:
    results22 = json.load(f)
    
with open('results_model_uq_v2/results_multi_task_mc_dropout.json') as f:
    results23 = json.load(f)

In [34]:
results11

{'value_los': [{'test/cal/ECE': 0.2575499713420868,
   'test/cal/aECE': 0.2575490474700928,
   'test/cls/Acc': 0.6686303615570068,
   'test/cls/Brier': 0.5645043849945068,
   'test/cls/NLL': 1.5252737998962402,
   'test/sc/AUGRC': 0.13935041427612305,
   'test/sc/AURC': 0.25735560059547424,
   'test/sc/Cov@5Risk': nan,
   'test/sc/Risk@80Cov': 0.29202455282211304,
   'test/cls/Entropy': 0.17401139438152313,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.17401139438152313,
   'test/ens_MI': 0.0}],
 'value_icu': [{'test/cal/ECE': 0.05300044268369675,
   'test/cal/aECE': 0.052696965634822845,
   'test/cls/Acc': 0.9170348644256592,
   'test/cls/Brier': 0.1388426423072815,
   'test/cls/NLL': 0.4265942871570587,
   'test/sc/AUGRC': 0.023714639246463776,
   'test/sc/AURC': 0.046523164957761765,
   'test/sc/Cov@5Risk': 0.8664703369140625,
   'test/sc/Risk@80Cov': 0.0441717803478241,
   'test/cls/Entropy': 0.07404477149248123,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.07404477149248123,
   'test/ens_MI': 0.0}],
 'value_hypoglycemia': [{'test/cal/ECE': 0.48612767457962036,
   'test/cal/aECE': 0.4857371151447296,
   'test/cls/Acc': 0.9858076572418213,
   'test/cls/Brier': 0.5001905560493469,
   'test/cls/NLL': 0.6934739351272583,
   'test/sc/AUGRC': 0.0072923507541418076,
   'test/sc/AURC': 0.01676371693611145,
   'test/sc/Cov@5Risk': nan,
   'test/sc/Risk@80Cov': 0.013680936768651009,
   'test/cls/Entropy': 0.693086564540863,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.693086564540863,
   'test/ens_MI': 0.0}],
 'value_hyperkalemia': [{'test/cal/ECE': 0.4808821380138397,
   'test/cal/aECE': 0.47963470220565796,
   'test/cls/Acc': 0.9798608422279358,
   'test/cls/Brier': 0.5005603432655334,
   'test/cls/NLL': 0.6939103007316589,
   'test/sc/AUGRC': 0.010251736268401146,
   'test/sc/AURC': 0.024823671206831932,
   'test/sc/Cov@5Risk': nan,
   'test/sc/Risk@80Cov': 0.01945381611585617,
   'test/cls/Entropy': 0.6929826736450195,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.6929826736450195,
   'test/ens_MI': 0.0}],
 'value_hyponatremia': [{'test/cal/ECE': 0.2726876139640808,
   'test/cal/aECE': 0.27059221267700195,
   'test/cls/Acc': 0.6091522574424744,
   'test/cls/Brier': 0.6345344185829163,
   'test/cls/NLL': 1.4091790914535522,
   'test/sc/AUGRC': 0.1851089596748352,
   'test/sc/AURC': 0.35147812962532043,
   'test/sc/Cov@5Risk': nan,
   'test/sc/Risk@80Cov': 0.3874419927597046,
   'test/cls/Entropy': 0.3063524663448334,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.3063524663448334,
   'test/ens_MI': 0.0}],
 'value_anemia': [{'test/cal/ECE': 0.3162359893321991,
   'test/cal/aECE': 0.31622326374053955,
   'test/cls/Acc': 0.5734711289405823,
   'test/cls/Brier': 0.7079351544380188,
   'test/cls/NLL': 1.6923682689666748,
   'test/sc/AUGRC': 0.19952760636806488,
   'test/sc/AURC': 0.3819811940193176,
   'test/sc/Cov@5Risk': nan,
   'test/sc/Risk@80Cov': 0.4114561378955841,
   'test/cls/Entropy': 0.24727044999599457,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.24727044999599457,
   'test/ens_MI': 0.0}],
 'value_thrombocytopenia': [{'test/cal/ECE': 0.321271151304245,
   'test/cal/aECE': 0.321050226688385,
   'test/cls/Acc': 0.5699704885482788,
   'test/cls/Brier': 0.7212293148040771,
   'test/cls/NLL': 1.7920506000518799,
   'test/sc/AUGRC': 0.20769457519054413,
   'test/sc/AURC': 0.4031449854373932,
   'test/sc/Cov@5Risk': nan,
   'test/sc/Risk@80Cov': 0.4248998165130615,
   'test/cls/Entropy': 0.2579648196697235,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.2579648196697235,
   'test/ens_MI': 0.0}],
 'value_new_hypertension': [{'test/cal/ECE': 0.11494375765323639,
   'test/cal/aECE': 0.11337132751941681,
   'test/cls/Acc': 0.8464163541793823,
   'test/cls/Brier': 0.2762640416622162,
   'test/cls/NLL': 0.8391852378845215,
   'test/sc/AUGRC': 0.060184989124536514,
   'test/sc/AURC': 0.10764740407466888,
   'test/sc/Cov@5Risk': nan,
   'test/sc/Risk@80Cov': 0.12642045319080353,
   'test/cls/Entropy': 0.09922380745410919,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.09922380745410919,
   'test/ens_MI': 0.0}],
 'value_new_hyperlipidemia': [{'test/cal/ECE': 0.11572067439556122,
   'test/cal/aECE': 0.11108722537755966,
   'test/cls/Acc': 0.8657565712928772,
   'test/cls/Brier': 0.24952487647533417,
   'test/cls/NLL': 0.8228746652603149,
   'test/sc/AUGRC': 0.04934098199009895,
   'test/sc/AURC': 0.1015000194311142,
   'test/sc/Cov@5Risk': nan,
   'test/sc/Risk@80Cov': 0.09801136702299118,
   'test/cls/Entropy': 0.0865628570318222,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.0865628570318222,
   'test/ens_MI': 0.0}],
 'value_new_acutemi': [{'test/cal/ECE': 0.03152329474687576,
   'test/cal/aECE': 0.02824423648416996,
   'test/cls/Acc': 0.9544937610626221,
   'test/cls/Brier': 0.07690741121768951,
   'test/cls/NLL': 0.24804970622062683,
   'test/sc/AUGRC': 0.010538221336901188,
   'test/sc/AURC': 0.01851464807987213,
   'test/sc/Cov@5Risk': 1.0,
   'test/sc/Risk@80Cov': 0.02130681835114956,
   'test/cls/Entropy': 0.040897585451602936,
   'test/ens_Disagreement': nan,
   'test/ens_Entropy': 0.040897585451602936,
   'test/ens_MI': 0.0}]}

In [35]:
df11 = read_results(results11)
df12 = read_results(results12)

df21 = read_results(results21)
df22 = read_results(results22)

df13 = read_results(results13)
df23 = read_results(results23)

In [36]:
df_single = pd.concat([df11, df12, df13], axis = 1)
df_single

,test/cls/Acc,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE,test/cls/Acc,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE,test/cls/Acc,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE
value_los,0.6686,0.5645,1.5253,0.2575,0.2575,0.6814,0.4942,0.8746,0.1661,0.1696,0.6780,0.5416,1.3656,0.2232,0.2265
value_icu,0.9170,0.1388,0.4266,0.0530,0.0527,0.9470,0.1013,0.3291,0.0425,0.0411,0.9411,0.1108,0.4432,0.0500,0.0424
value_hypoglycemia,0.9858,0.5002,0.6935,0.4861,0.4857,0.9800,0.0395,0.1364,0.0183,0.0219,0.9851,0.5004,0.6938,0.4858,0.4849
value_hyperkalemia,0.9799,0.5006,0.6939,0.4809,0.4796,0.9754,0.0496,0.1772,0.0252,0.0272,0.9802,0.5002,0.6933,0.4806,0.4801
value_hyponatremia,0.6092,0.6345,1.4092,0.2727,0.2706,0.6183,0.5160,0.7986,0.1357,0.1357,0.5882,0.6178,1.1984,0.2399,0.2400
value_anemia,0.5735,0.7079,1.6924,0.3162,0.3162,0.5942,0.5613,0.9057,0.1748,0.1748,0.5595,0.6701,1.3312,0.2745,0.2745
value_thrombocytopenia,0.5700,0.7212,1.7921,0.3213,0.3211,0.5754,0.5888,0.9668,0.1986,0.1986,0.5680,0.6673,1.4020,0.2750,0.2737
value_new_hypertension,0.8464,0.2763,0.8392,0.1149,0.1134,0.8544,0.2587,0.5458,0.0905,0.0893,0.8510,0.2756,0.7987,0.1181,0.1101
value_new_hyperlipidemia,0.8658,0.2495,0.8229,0.1157,0.1111,0.8771,0.2187,0.5106,0.0825,0.0810,0.8578,0.2453,0.7004,0.1051,0.0967
value_new_acutemi,0.9545,0.0769,0.2480,0.0315,0.0282,0.9625,0.0690,0.1676,0.0302,0.0226,0.9488,0.0900,0.2308,0.0339,0.0268

In [37]:
df_multiple = pd.concat([df21, df22, df23], axis=1)
df_multiple

,test/cls/Acc,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE,test/cls/Acc,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE,test/cls/Acc,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE
value_los,0.6328,0.6215,1.5723,0.2798,0.2789,0.6529,0.5257,0.9421,0.1890,0.1896,0.6519,0.5703,1.3140,0.2381,0.2381
value_icu,0.9485,0.0993,0.7288,0.0477,0.0466,0.9524,0.0922,0.3905,0.0399,0.0382,0.9494,0.0969,0.6399,0.0455,0.0418
value_hypoglycemia,0.9859,0.0344,0.1532,0.0199,0.0227,0.9861,0.0301,0.0947,0.0108,0.0203,0.9858,0.0369,0.1293,0.0231,0.0300
value_hyperkalemia,0.9803,0.0459,0.1692,0.0246,0.0284,0.9808,0.0408,0.1197,0.0155,0.0234,0.9802,0.0474,0.1490,0.0272,0.0325
value_hyponatremia,0.7227,0.5001,0.6945,0.2230,0.2208,0.5708,0.5020,0.6972,0.0787,0.0882,0.7201,0.4959,0.6929,0.2119,0.2067
value_anemia,0.6372,0.5649,1.1548,0.2236,0.2225,0.6819,0.5047,0.8144,0.1702,0.1701,0.6588,0.5242,0.9476,0.1767,0.1757
value_thrombocytopenia,0.5587,0.6797,1.3099,0.2856,0.2824,0.5527,0.5605,0.8118,0.1586,0.1586,0.5496,0.6386,1.0853,0.2379,0.2366
value_new_hypertension,0.8453,0.2778,0.9824,0.1213,0.1205,0.8487,0.2549,0.5810,0.0903,0.0793,0.8578,0.2601,0.8215,0.1075,0.1019
value_new_hyperlipidemia,0.8635,0.2503,1.0269,0.1151,0.1147,0.8578,0.2410,0.6209,0.0936,0.0927,0.8794,0.2283,0.9220,0.1023,0.0944
value_new_acutemi,0.9659,0.0636,0.3306,0.0299,0.0258,0.9670,0.0615,0.1892,0.0276,0.0252,0.9602,0.0675,0.3405,0.0292,0.0289

In [91]:
b = format_latex_with_color(df_single, df_multiple)
print(b)

& \cellcolor{gray!12}0.5645 & \cellcolor{gray!12}1.5253 & \cellcolor{gray!12}0.2575 & \cellcolor{gray!12}0.2575 & \cellcolor{gray!12}0.4942 & \cellcolor{gray!12}0.8746 & \cellcolor{gray!12}0.1661 & \cellcolor{gray!12}0.1696 & \cellcolor{gray!12}0.5416 & 1.3656 & \cellcolor{gray!12}0.2232 & \cellcolor{gray!12}0.2265 \\
& 0.1388 & \cellcolor{gray!12}0.4266 & 0.0530 & 0.0527 & 0.1013 & \cellcolor{gray!12}0.3291 & 0.0425 & 0.0411 & 0.1108 & \cellcolor{gray!12}0.4432 & 0.0500 & 0.0424 \\
& 0.5002 & 0.6935 & 0.4861 & 0.4857 & 0.0395 & 0.1364 & 0.0183 & 0.0219 & 0.5004 & 0.6938 & 0.4858 & 0.4849 \\
& 0.5006 & 0.6939 & 0.4809 & 0.4796 & 0.0496 & 0.1772 & 0.0252 & 0.0272 & 0.5002 & 0.6933 & 0.4806 & 0.4801 \\
& 0.6345 & 1.4092 & 0.2727 & 0.2706 & 0.5160 & 0.7986 & 0.1357 & 0.1357 & 0.6178 & 1.1984 & 0.2399 & 0.2400 \\
& 0.7079 & 1.6924 & 0.3162 & 0.3162 & 0.5613 & 0.9057 & 0.1748 & 0.1748 & 0.6701 & 1.3312 & 0.2745 & 0.2745 \\
& 0.7212 & 1.7921 & 0.3213 & 0.3211 & 0.5888 & 0.9668 & 0.1986 & 0.1986 & 0.6673 & 1.4020 & 0.2750 & 0.2737 \\
& \cellcolor{gray!12}0.2763 & \cellcolor{gray!12}0.8392 & \cellcolor{gray!12}0.1149 & \cellcolor{gray!12}0.1134 & 0.2587 & \cellcolor{gray!12}0.5458 & 0.0905 & 0.0893 & 0.2756 & \cellcolor{gray!12}0.7987 & 0.1181 & 0.1101 \\
& \cellcolor{gray!12}0.2495 & \cellcolor{gray!12}0.8229 & 0.1157 & \cellcolor{gray!12}0.1111 & \cellcolor{gray!12}0.2187 & \cellcolor{gray!12}0.5106 & \cellcolor{gray!12}0.0825 & \cellcolor{gray!12}0.0810 & 0.2453 & \cellcolor{gray!12}0.7004 & 0.1051 & 0.0967 \\
& 0.0769 & \cellcolor{gray!12}0.2480 & 0.0315 & 0.0282 & 0.0690 & \cellcolor{gray!12}0.1676 & 0.0302 & \cellcolor{gray!12}0.0226 & 0.0900 & \cellcolor{gray!12}0.2308 & 0.0339 & \cellcolor{gray!12}0.0268 \\
& 0.6215 & 1.5723 & 0.2798 & 0.2789 & 0.5257 & 0.9421 & 0.1890 & 0.1896 & 0.5703 & \cellcolor{gray!12}1.3140 & 0.2381 & 0.2381 \\
& \cellcolor{gray!12}0.0993 & 0.7288 & \cellcolor{gray!12}0.0477 & \cellcolor{gray!12}0.0466 & \cellcolor{gray!12}0.0922 & 0.3905 & \cellcolor{gray!12}0.0399 & \cellcolor{gray!12}0.0382 & \cellcolor{gray!12}0.0969 & 0.6399 & \cellcolor{gray!12}0.0455 & \cellcolor{gray!12}0.0418 \\
& \cellcolor{gray!12}0.0344 & \cellcolor{gray!12}0.1532 & \cellcolor{gray!12}0.0199 & \cellcolor{gray!12}0.0227 & \cellcolor{gray!12}0.0301 & \cellcolor{gray!12}0.0947 & \cellcolor{gray!12}0.0108 & \cellcolor{gray!12}0.0203 & \cellcolor{gray!12}0.0369 & \cellcolor{gray!12}0.1293 & \cellcolor{gray!12}0.0231 & \cellcolor{gray!12}0.0300 \\
& \cellcolor{gray!12}0.0459 & \cellcolor{gray!12}0.1692 & \cellcolor{gray!12}0.0246 & \cellcolor{gray!12}0.0284 & \cellcolor{gray!12}0.0408 & \cellcolor{gray!12}0.1197 & \cellcolor{gray!12}0.0155 & \cellcolor{gray!12}0.0234 & \cellcolor{gray!12}0.0474 & \cellcolor{gray!12}0.1490 & \cellcolor{gray!12}0.0272 & \cellcolor{gray!12}0.0325 \\
& \cellcolor{gray!12}0.5001 & \cellcolor{gray!12}0.6945 & \cellcolor{gray!12}0.2230 & \cellcolor{gray!12}0.2208 & \cellcolor{gray!12}0.5020 & \cellcolor{gray!12}0.6972 & \cellcolor{gray!12}0.0787 & \cellcolor{gray!12}0.0882 & \cellcolor{gray!12}0.4959 & \cellcolor{gray!12}0.6929 & \cellcolor{gray!12}0.2119 & \cellcolor{gray!12}0.2067 \\
& \cellcolor{gray!12}0.5649 & \cellcolor{gray!12}1.1548 & \cellcolor{gray!12}0.2236 & \cellcolor{gray!12}0.2225 & \cellcolor{gray!12}0.5047 & \cellcolor{gray!12}0.8144 & \cellcolor{gray!12}0.1702 & \cellcolor{gray!12}0.1701 & \cellcolor{gray!12}0.5242 & \cellcolor{gray!12}0.9476 & \cellcolor{gray!12}0.1767 & \cellcolor{gray!12}0.1757 \\
& \cellcolor{gray!12}0.6797 & \cellcolor{gray!12}1.3099 & \cellcolor{gray!12}0.2856 & \cellcolor{gray!12}0.2824 & \cellcolor{gray!12}0.5605 & \cellcolor{gray!12}0.8118 & \cellcolor{gray!12}0.1586 & \cellcolor{gray!12}0.1586 & \cellcolor{gray!12}0.6386 & \cellcolor{gray!12}1.0853 & \cellcolor{gray!12}0.2379 & \cellcolor{gray!12}0.2366 \\
& 0.2778 & 0.9824 & 0.1213 & 0.1205 & \cellcolor{gray!12}0.2549 & 0.5810 & \cellcolor{gray!12}0.0903 & \cellcolor{gray!12}0.0793 & \cellcolor{gray!12}0.2601 & 0.8215 & \cellcolor{gray!12}0.1075 & \cellcolor{gray!12}0.1019 \\
& 0.2503 & 1.0269 & \cellcolor{gray!12}0.1151 & 0.1147 & 0.2410 & 0.6209 & 0.0936 & 0.0927 & \cellcolor{gray!12}0.2283 & 0.9220 & \cellcolor{gray!12}0.1023 & \cellcolor{gray!12}0.0944 \\
& \cellcolor{gray!12}0.0636 & 0.3306 & \cellcolor{gray!12}0.0299 & \cellcolor{gray!12}0.0258 & \cellcolor{gray!12}0.0615 & 0.1892 & \cellcolor{gray!12}0.0276 & 0.0252 & \cellcolor{gray!12}0.0675 & 0.3405 & \cellcolor{gray!12}0.0292 & 0.0289 \\

In [60]:
def df_to_latex(df):
    latex_str = ""
    for index, row in df.iterrows():
        # Create a string for each row and append it to the main string
        row_str = " & " + " & ".join([f"{val:.4f}" for val in row]) + " \\\\\n"
        latex_str += row_str
    return latex_str

In [63]:
a = df_to_latex(df_multiple)
print(a)

 & 0.6215 & 1.5723 & 0.2798 & 0.2789 & 0.5257 & 0.9421 & 0.1890 & 0.1896 & 0.5703 & 1.3140 & 0.2381 & 0.2381 \\
 & 0.0993 & 0.7288 & 0.0477 & 0.0466 & 0.0922 & 0.3905 & 0.0399 & 0.0382 & 0.0969 & 0.6399 & 0.0455 & 0.0418 \\
 & 0.0344 & 0.1532 & 0.0199 & 0.0227 & 0.0301 & 0.0947 & 0.0108 & 0.0203 & 0.0369 & 0.1293 & 0.0231 & 0.0300 \\
 & 0.0459 & 0.1692 & 0.0246 & 0.0284 & 0.0408 & 0.1197 & 0.0155 & 0.0234 & 0.0474 & 0.1490 & 0.0272 & 0.0325 \\
 & 0.5001 & 0.6945 & 0.2230 & 0.2208 & 0.5020 & 0.6972 & 0.0787 & 0.0882 & 0.4959 & 0.6929 & 0.2119 & 0.2067 \\
 & 0.5649 & 1.1548 & 0.2236 & 0.2225 & 0.5047 & 0.8144 & 0.1702 & 0.1701 & 0.5242 & 0.9476 & 0.1767 & 0.1757 \\
 & 0.6797 & 1.3099 & 0.2856 & 0.2824 & 0.5605 & 0.8118 & 0.1586 & 0.1586 & 0.6386 & 1.0853 & 0.2379 & 0.2366 \\
 & 0.2778 & 0.9824 & 0.1213 & 0.1205 & 0.2549 & 0.5810 & 0.0903 & 0.0793 & 0.2601 & 0.8215 & 0.1075 & 0.1019 \\
 & 0.2503 & 1.0269 & 0.1151 & 0.1147 & 0.2410 & 0.6209 & 0.0936 & 0.0927 & 0.2283 & 0.9220 & 0.1023 & 0.0944 \\
 & 0.0636 & 0.3306 & 0.0299 & 0.0258 & 0.0615 & 0.1892 & 0.0276 & 0.0252 & 0.0675 & 0.3405 & 0.0292 & 0.0289 \\

In [37]:
pd.concat([df11, df21], axis = 1)

,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE
value_los,0.5645,1.5253,0.2575,0.2575,0.6215,1.5723,0.2798,0.2789
value_icu,0.1388,0.4266,0.0530,0.0527,0.0993,0.7288,0.0477,0.0466
value_hypoglycemia,0.5002,0.6935,0.4861,0.4857,0.0344,0.1532,0.0199,0.0227
value_hyperkalemia,0.5006,0.6939,0.4809,0.4796,0.0459,0.1692,0.0246,0.0284
value_hyponatremia,0.6345,1.4092,0.2727,0.2706,0.5001,0.6945,0.2230,0.2208
value_anemia,0.7079,1.6924,0.3162,0.3162,0.5649,1.1548,0.2236,0.2225
value_thrombocytopenia,0.7212,1.7921,0.3213,0.3211,0.6797,1.3099,0.2856,0.2824
value_new_hypertension,0.2763,0.8392,0.1149,0.1134,0.2778,0.9824,0.1213,0.1205
value_new_hyperlipidemia,0.2495,0.8229,0.1157,0.1111,0.2503,1.0269,0.1151,0.1147
value_new_acutemi,0.0769,0.2480,0.0315,0.0282,0.0636,0.3306,0.0299,0.0258

In [38]:
pd.concat([df12, df22], axis = 1)

,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE
value_los,0.4942,0.8746,0.1661,0.1696,0.5257,0.9421,0.1890,0.1896
value_icu,0.1013,0.3291,0.0425,0.0411,0.0922,0.3905,0.0399,0.0382
value_hypoglycemia,0.0395,0.1364,0.0183,0.0219,0.0301,0.0947,0.0108,0.0203
value_hyperkalemia,0.0496,0.1772,0.0252,0.0272,0.0408,0.1197,0.0155,0.0234
value_hyponatremia,0.5160,0.7986,0.1357,0.1357,0.5020,0.6972,0.0787,0.0882
value_anemia,0.5613,0.9057,0.1748,0.1748,0.5047,0.8144,0.1702,0.1701
value_thrombocytopenia,0.5888,0.9668,0.1986,0.1986,0.5605,0.8118,0.1586,0.1586
value_new_hypertension,0.2587,0.5458,0.0905,0.0893,0.2549,0.5810,0.0903,0.0793
value_new_hyperlipidemia,0.2187,0.5106,0.0825,0.0810,0.2410,0.6209,0.0936,0.0927
value_new_acutemi,0.0690,0.1676,0.0302,0.0226,0.0615,0.1892,0.0276,0.0252

In [39]:
pd.concat([df13, df23], axis = 1)

,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/ECE,test/cal/aECE
value_los,0.5416,1.3656,0.2232,0.2265,0.5703,1.3140,0.2381,0.2381
value_icu,0.1108,0.4432,0.0500,0.0424,0.0969,0.6399,0.0455,0.0418
value_hypoglycemia,0.5004,0.6938,0.4858,0.4849,0.0369,0.1293,0.0231,0.0300
value_hyperkalemia,0.5002,0.6933,0.4806,0.4801,0.0474,0.1490,0.0272,0.0325
value_hyponatremia,0.6178,1.1984,0.2399,0.2400,0.4959,0.6929,0.2119,0.2067
value_anemia,0.6701,1.3312,0.2745,0.2745,0.5242,0.9476,0.1767,0.1757
value_thrombocytopenia,0.6673,1.4020,0.2750,0.2737,0.6386,1.0853,0.2379,0.2366
value_new_hypertension,0.2756,0.7987,0.1181,0.1101,0.2601,0.8215,0.1075,0.1019
value_new_hyperlipidemia,0.2453,0.7004,0.1051,0.0967,0.2283,0.9220,0.1023,0.0944
value_new_acutemi,0.0900,0.2308,0.0339,0.0268,0.0675,0.3405,0.0292,0.0289

In [13]:
with open('results_model_uq/results_multi_task_deep_ensemble.json') as f:
    result12 = json.load(f)
result12

{'guo_los': [{'test/cal/ECE': 0.024611974135041237,
   'test/cal/aECE': 0.029376156628131866,
   'test/cls/Acc': 0.7722095847129822,
   'test/cls/Brier': 0.3092302978038788,
   'test/cls/NLL': 0.46678590774536133,
   'test/sc/AUGRC': 0.07117360830307007,
   'test/sc/AURC': 0.10189932584762573,
   'test/sc/CovAt5Risk': nan,
   'test/sc/RiskAt80Cov': 0.17653758823871613,
   'test/cls/entropy': 0.43543627858161926,
   'test/ens_Disagreement': 0.10897494852542877,
   'test/ens_Entropy': 0.41884320974349976,
   'test/ens_MI': 0.01659310795366764}],
 'guo_readmission': [{'test/cal/ECE': 0.0202920064330101,
   'test/cal/aECE': 0.02200198546051979,
   'test/cls/Acc': 0.8560986518859863,
   'test/cls/Brier': 0.2057093381881714,
   'test/cls/NLL': 0.33692145347595215,
   'test/sc/AUGRC': 0.03481394052505493,
   'test/sc/AURC': 0.049600474536418915,
   'test/sc/CovAt5Risk': 0.5701233148574829,
   'test/sc/RiskAt80Cov': 0.07876712083816528,
   'test/cls/entropy': 0.3312183916568756,
   'test/ens_Disagreement': 0.08594891428947449,
   'test/ens_Entropy': 0.3694774806499481,
   'test/ens_MI': 0.013921227306127548}],
 'guo_icu': [{'test/cal/ECE': 0.022255832329392433,
   'test/cal/aECE': 0.018611354753375053,
   'test/cls/Acc': 0.9567992091178894,
   'test/cls/Brier': 0.0716664046049118,
   'test/cls/NLL': 0.13692019879817963,
   'test/sc/AUGRC': 0.006501287221908569,
   'test/sc/AURC': 0.008389070630073547,
   'test/sc/CovAt5Risk': 1.0,
   'test/sc/RiskAt80Cov': 0.016564417630434036,
   'test/cls/entropy': 0.1673591434955597,
   'test/ens_Disagreement': 0.06453824043273926,
   'test/ens_Entropy': 0.30366215109825134,
   'test/ens_MI': 0.011199994012713432}],
 'new_hypertension': [{'test/cal/ECE': 0.02537129446864128,
   'test/cal/aECE': 0.03937491029500961,
   'test/cls/Acc': 0.7090619802474976,
   'test/cls/Brier': 0.37440288066864014,
   'test/cls/NLL': 0.5533531308174133,
   'test/sc/AUGRC': 0.10515041649341583,
   'test/sc/AURC': 0.16641879081726074,
   'test/sc/CovAt5Risk': nan,
   'test/sc/RiskAt80Cov': 0.24627606570720673,
   'test/cls/entropy': 0.5254281759262085,
   'test/ens_Disagreement': 0.16661366820335388,
   'test/ens_Entropy': 0.5044287443161011,
   'test/ens_MI': 0.020999349653720856}],
 'new_hyperlipidemia': [{'test/cal/ECE': 0.03262944892048836,
   'test/cal/aECE': 0.03171534091234207,
   'test/cls/Acc': 0.7342444658279419,
   'test/cls/Brier': 0.3607196807861328,
   'test/cls/NLL': 0.5403991341590881,
   'test/sc/AUGRC': 0.09751424938440323,
   'test/sc/AURC': 0.15953794121742249,
   'test/sc/CovAt5Risk': nan,
   'test/sc/RiskAt80Cov': 0.21821631491184235,
   'test/cls/entropy': 0.5254315733909607,
   'test/ens_Disagreement': 0.16885437071323395,
   'test/ens_Entropy': 0.504003643989563,
   'test/ens_MI': 0.02142619527876377}],
 'new_pancan': [{'test/cal/ECE': 0.09146346151828766,
   'test/cal/aECE': 0.09173661470413208,
   'test/cls/Acc': 0.9130630493164062,
   'test/cls/Brier': 0.1464819759130478,
   'test/cls/NLL': 0.2658914625644684,
   'test/sc/AUGRC': 0.013550152070820332,
   'test/sc/AURC': 0.01919526793062687,
   'test/sc/CovAt5Risk': 0.911261260509491,
   'test/sc/RiskAt80Cov': 0.026463963091373444,
   'test/cls/entropy': 0.40563827753067017,
   'test/ens_Disagreement': 0.13017728924751282,
   'test/ens_Entropy': 0.449121356010437,
   'test/ens_MI': 0.02084716223180294}],
 'new_celiac': [{'test/cal/ECE': 0.10780403763055801,
   'test/cal/aECE': 0.10780397057533264,
   'test/cls/Acc': 0.984698474407196,
   'test/cls/Brier': 0.064488984644413,
   'test/cls/NLL': 0.15524917840957642,
   'test/sc/AUGRC': 0.0027645041700452566,
   'test/sc/AURC': 0.0038599686231464148,
   'test/sc/CovAt5Risk': 1.0,
   'test/sc/RiskAt80Cov': 0.007311585824936628,
   'test/cls/entropy': 0.324566513299942,
   'test/ens_Disagreement': 0.09539692848920822,
   'test/ens_Entropy': 0.4059488773345947,
   'test/ens_MI': 0.017976602539420128}],
 'new_lupus': [{'test/cal/ECE': 0.1314271092414856,
   'test/cal/aECE': 0.13142701983451843,
   'test/cls/Acc': 0.9719126224517822,
   'test/cls/Brier': 0.09827513992786407,
   'test/cls/NLL': 0.20669031143188477,
   'test/sc/AUGRC': 0.004347055219113827,
   'test/sc/AURC': 0.007225468289107084,
   'test/sc/CovAt5Risk': 1.0,
   'test/sc/RiskAt80Cov': 0.008356546051800251,
   'test/cls/entropy': 0.37891584634780884,
   'test/ens_Disagreement': 0.08777540177106857,
   'test/ens_Entropy': 0.39495450258255005,
   'test/ens_MI': 0.018068557605147362}],
 'new_acutemi': [{'test/cal/ECE': 0.08680018037557602,
   'test/cal/aECE': 0.08680017292499542,
   'test/cls/Acc': 0.8542548418045044,
   'test/cls/Brier': 0.23653309047222137,
   'test/cls/NLL': 0.38568490743637085,
   'test/sc/AUGRC': 0.03956123813986778,
   'test/sc/AURC': 0.05752689391374588,
   'test/sc/CovAt5Risk': nan,
   'test/sc/RiskAt80Cov': 0.08930669724941254,
   'test/cls/entropy': 0.48502403497695923,
   'test/ens_Disagreement': 0.09412491321563721,
   'test/ens_Entropy': 0.40782445669174194,
   'test/ens_MI': 0.018647808581590652}],
 'lab_thrombocytopenia': [{'test/cal/ECE': 0.03668219596147537,
   'test/cal/aECE': 0.0363360270857811,
   'test/cls/Acc': 0.754357635974884,
   'test/cls/Brier': 0.3322187066078186,
   'test/cls/NLL': 0.5009514093399048,
   'test/sc/AUGRC': 0.08119658380746841,
   'test/sc/AURC': 0.1227237805724144,
   'test/sc/CovAt5Risk': nan,
   'test/sc/RiskAt80Cov': 0.19362783432006836,
   'test/cls/entropy': 0.5419284105300903,
   'test/ens_Disagreement': 0.1378536820411682,
   'test/ens_Entropy': 0.5270607471466064,
   'test/ens_MI': 0.014867412857711315}],
 'lab_hyperkalemia': [{'test/cal/ECE': 0.06208276376128197,
   'test/cal/aECE': 0.06223297119140625,
   'test/cls/Acc': 0.9744238257408142,
   'test/cls/Brier': 0.05977554991841316,
   'test/cls/NLL': 0.1384868621826172,
   'test/sc/AUGRC': 0.0056398347951471806,
   'test/sc/AURC': 0.009189602918922901,
   'test/sc/CovAt5Risk': 1.0,
   'test/sc/RiskAt80Cov': 0.012273432686924934,
   'test/cls/entropy': 0.256296306848526,
   'test/ens_Disagreement': 0.06910014152526855,
   'test/ens_Entropy': 0.3783855736255646,
   'test/ens_MI': 0.012019801884889603}],
 'lab_hyponatremia': [{'test/cal/ECE': 0.01860152930021286,
   'test/cal/aECE': 0.021093159914016724,
   'test/cls/Acc': 0.680521547794342,
   'test/cls/Brier': 0.39872798323631287,
   'test/cls/NLL': 0.5800139904022217,
   'test/sc/AUGRC': 0.12105714529752731,
   'test/sc/AURC': 0.19205141067504883,
   'test/sc/CovAt5Risk': nan,
   'test/sc/RiskAt80Cov': 0.27889153361320496,
   'test/cls/entropy': 0.6016912460327148,
   'test/ens_Disagreement': 0.10494773834943771,
   'test/ens_Entropy': 0.4536472260951996,
   'test/ens_MI': 0.01248305942863226}],
 'lab_anemia': [{'test/cal/ECE': 0.01702522486448288,
   'test/cal/aECE': 0.01702372543513775,
   'test/cls/Acc': 0.8863554000854492,
   'test/cls/Brier': 0.15865087509155273,
   'test/cls/NLL': 0.2545349597930908,
   'test/sc/AUGRC': 0.019472813233733177,
   'test/sc/AURC': 0.023735983297228813,
   'test/sc/CovAt5Risk': 0.8122431635856628,
   'test/sc/RiskAt80Cov': 0.04681454598903656,
   'test/cls/entropy': 0.28845033049583435,
   'test/ens_Disagreement': 0.0900627076625824,
   'test/ens_Entropy': 0.4131181538105011,
   'test/ens_MI': 0.010867182165384293}],
 'lab_hypoglycemia': [{'test/cal/ECE': 0.042217060923576355,
   'test/cal/aECE': 0.04226117581129074,
   'test/cls/Acc': 0.9862580299377441,
   'test/cls/Brier': 0.0341554619371891,
   'test/cls/NLL': 0.09065066277980804,
   'test/sc/AUGRC': 0.003253798233345151,
   'test/sc/AURC': 0.0050855884328484535,
   'test/sc/CovAt5Risk': 1.0,
   'test/sc/RiskAt80Cov': 0.0072587160393595695,
   'test/cls/entropy': 0.1836288869380951,
   'test/ens_Disagreement': 0.0645749643445015,
   'test/ens_Entropy': 0.34409862756729126,
   'test/ens_MI': 0.009972532279789448}]}

In [15]:
# df_single = read_results(results11)
# df_multi = read_results(results12)
# df1 = pd.concat([df_single, df_multi], axis=1).round(4)

# df_single = read_results(results21)
# df_multi = read_results(results22)
# df2 = pd.concat([df_single, df_multi], axis=1).round(4)

# df_single_1 = read_results(results31)
# df_single_2 = read_results(results32)
# df_multi = read_results(results33)
# df_single = pd.concat([df_single_1, df_single_2], axis=0)
# df3 = pd.concat([df_single, df_multi], axis=1).round(4)

df1 = read_results(results11)
df2 = read_results(results12)
df12 = pd.concat([df1, df2], axis=1).round(4)

df3 = read_results(results21)
df4= read_results(results22)
df34 = pd.concat([df3, df4], axis=1).round(4)

df_single_1 = read_results(results31)
df_single_2 = read_results(results32)
df6= read_results(results33)
df5 = pd.concat([df_single_1, df_single_2], axis=0)
df56 = pd.concat([df5, df6], axis=1).round(4)

In [16]:
df_all = pd.concat([df1, df3, df5, df2, df4, df6], axis=1)
df_all

,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE
guo_los,0.2938,0.4450,0.0315,0.3418,0.5205,0.0827,0.3225,0.4839,0.0324,0.3092,0.4668,0.0294,0.3217,0.5942,0.0995,0.7230,1.0068,0.3254
guo_readmission,0.2036,0.3328,0.0218,0.2431,0.4142,0.1125,0.2510,0.3976,0.0316,0.2057,0.3369,0.0220,0.2133,0.4799,0.0725,0.3842,0.5651,0.0404
guo_icu,0.0867,0.1566,0.0093,0.1508,0.2954,0.1702,0.1210,0.2067,0.0228,0.0717,0.1369,0.0186,0.0726,0.2176,0.0273,0.5505,0.7601,0.1951
new_hypertension,0.2699,0.4350,0.0356,0.2669,0.4497,0.0979,0.2876,0.4624,0.0529,0.3744,0.5534,0.0394,0.2417,0.4662,0.0677,0.4238,0.6161,0.2728
new_hyperlipidemia,0.2510,0.4123,0.0491,0.2722,0.4683,0.1059,0.2971,0.4618,0.0410,0.3607,0.5404,0.0317,0.2474,0.5244,0.0727,0.4252,0.6175,0.2715
new_pancan,0.1032,0.1792,0.0195,0.1403,0.2811,0.1914,0.1649,0.2686,0.0280,0.1465,0.2659,0.0917,0.0450,0.1058,0.0155,0.4027,0.5950,0.3843
new_celiac,0.0631,0.1355,0.0503,0.1190,0.2573,0.1981,0.1052,0.2008,0.0640,0.0645,0.1552,0.1078,0.0205,0.0660,0.0146,0.3985,0.5908,0.3973
new_lupus,0.0701,0.1364,0.0360,0.1281,0.2682,0.1975,0.1062,0.1937,0.0497,0.0983,0.2067,0.1314,0.0241,0.0685,0.0230,0.3983,0.5905,0.3957
new_acutemi,0.1616,0.2832,0.0224,0.2129,0.3695,0.1335,0.2494,0.3948,0.0167,0.2365,0.3857,0.0868,0.1282,0.2800,0.0393,0.4126,0.6049,0.3373
lab_thrombocytopenia,0.3047,0.4688,0.0137,0.3373,0.5223,0.0654,0.3176,0.4890,0.0539,0.3322,0.5010,0.0363,0.2964,0.4690,0.0355,0.6276,0.8360,0.2823
lab_hyperkalemia,0.1110,0.2024,0.0568,0.1383,0.2819,0.1829,0.2300,0.3858,0.1212,0.0598,0.1385,0.0622,0.0465,0.1089,0.0073,0.7719,0.9888,0.4725
lab_hyponatremia,0.3697,0.5470,0.0084,0.3827,0.5719,0.0475,0.4131,0.6010,0.0390,0.3987,0.5800,0.0211,0.3564,0.5430,0.0478,0.6844,0.9033,0.3305
lab_anemia,0.1466,0.2373,0.0075,0.2187,0.3757,0.1322,0.1557,0.2587,0.0145,0.1587,0.2545,0.0170,0.1472,0.2413,0.0106,0.3375,0.5038,0.1225
lab_hypoglycemia,0.0889,0.1734,0.0772,0.1238,0.2643,0.1907,0.2173,0.3916,0.2813,0.0342,0.0907,0.0423,0.0266,0.0705,0.0045,0.6935,0.8993,0.4020

In [17]:
column_names = ['Long Length of Stay', '30-day Readmission', 'ICU Transfer', 'Thrombocytopenia', 'Hyperkalemia', 'Hypoglycemia', 'Hyponatremia', 
                'Anemia', 'Hypertension', 'Hyperlipidemia', 'Pancreatic Cancer', 'Celiac', 'Lupus', 'Acute MI']
df_all.index = column_names

In [12]:
for i, (index, row) in enumerate(df_all11.iterrows()):
    # Create a LaTeX formatted string for each row
    latex_row = ' & '.join(map(str, row)) + ' \\\\'
    if i in [2, 8]:
        print('\midrule')
        print('\\vspace{-3mm}')
        print("\\\\")
    print('\hline ' + index + ' & ' + latex_row)

\hline value_los & 0.386 & 1.0315 & 0.1689 & 0.3505 & 0.6597 & 0.1408 & 0.3838 & 0.9356 & 0.1606 \\
\hline value_icu & 0.0922 & 0.3527 & 0.0399 & 0.0895 & 0.2236 & 0.0337 & 0.0902 & 0.2528 & 0.0346 \\
\midrule
\vspace{-3mm}
\\
\hline value_hypoglycemia & 0.1001 & 0.1773 & 0.0748 & 0.0435 & 0.1175 & 0.0125 & 0.0756 & 0.1499 & 0.019 \\
\hline value_hyperkalemia & 0.0962 & 0.1995 & 0.0295 & 0.0549 & 0.1518 & 0.0134 & 0.0951 & 0.1817 & 0.0171 \\
\hline value_hyponatremia & 0.5081 & 1.2053 & 0.2189 & 0.4001 & 0.7026 & 0.1062 & 0.4849 & 1.0172 & 0.1854 \\
\hline value_anemia & 0.1897 & 0.5743 & 0.0825 & 0.1564 & 0.3264 & 0.0482 & 0.1806 & 0.4658 & 0.0677 \\
\hline value_thrombocytopenia & 0.4104 & 1.1414 & 0.18 & 0.3279 & 0.6504 & 0.0986 & 0.3869 & 0.8833 & 0.1465 \\
\hline value_new_hypertension & 0.3373 & 1.2112 & 0.1625 & 0.2758 & 0.6734 & 0.1134 & 0.3231 & 1.0734 & 0.148 \\
\midrule
\vspace{-3mm}
\\
\hline value_new_hyperlipidemia & 0.2557 & 0.872 & 0.112 & 0.2531 & 0.5729 & 0.1033 & 0.2699 & 0.8708 & 0.122 \\
\hline value_new_acutemi & 0.0972 & 0.3813 & 0.0458 & 0.0951 & 0.2738 & 0.036 & 0.1088 & 0.4123 & 0.0444 \\

In [ ]:
a

In [24]:
df_all

,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE
Long Length of Stay,0.2938,0.4450,0.0315,0.3418,0.5205,0.0827,0.3225,0.4839,0.0324,0.3092,0.4668,0.0294,0.3217,0.5942,0.0995,0.7230,1.0068,0.3254
30-day Readmission,0.2036,0.3328,0.0218,0.2431,0.4142,0.1125,0.2510,0.3976,0.0316,0.2057,0.3369,0.0220,0.2133,0.4799,0.0725,0.3842,0.5651,0.0404
ICU Transfer,0.0867,0.1566,0.0093,0.1508,0.2954,0.1702,0.1210,0.2067,0.0228,0.0717,0.1369,0.0186,0.0726,0.2176,0.0273,0.5505,0.7601,0.1951
Thrombocytopenia,0.2699,0.4350,0.0356,0.2669,0.4497,0.0979,0.2876,0.4624,0.0529,0.3744,0.5534,0.0394,0.2417,0.4662,0.0677,0.4238,0.6161,0.2728
Hyperkalemia,0.2510,0.4123,0.0491,0.2722,0.4683,0.1059,0.2971,0.4618,0.0410,0.3607,0.5404,0.0317,0.2474,0.5244,0.0727,0.4252,0.6175,0.2715
Hypoglycemia,0.1032,0.1792,0.0195,0.1403,0.2811,0.1914,0.1649,0.2686,0.0280,0.1465,0.2659,0.0917,0.0450,0.1058,0.0155,0.4027,0.5950,0.3843
Hyponatremia,0.0631,0.1355,0.0503,0.1190,0.2573,0.1981,0.1052,0.2008,0.0640,0.0645,0.1552,0.1078,0.0205,0.0660,0.0146,0.3985,0.5908,0.3973
Anemia,0.0701,0.1364,0.0360,0.1281,0.2682,0.1975,0.1062,0.1937,0.0497,0.0983,0.2067,0.1314,0.0241,0.0685,0.0230,0.3983,0.5905,0.3957
Hypertension,0.1616,0.2832,0.0224,0.2129,0.3695,0.1335,0.2494,0.3948,0.0167,0.2365,0.3857,0.0868,0.1282,0.2800,0.0393,0.4126,0.6049,0.3373
Hyperlipidemia,0.3047,0.4688,0.0137,0.3373,0.5223,0.0654,0.3176,0.4890,0.0539,0.3322,0.5010,0.0363,0.2964,0.4690,0.0355,0.6276,0.8360,0.2823
Pancreatic Cancer,0.1110,0.2024,0.0568,0.1383,0.2819,0.1829,0.2300,0.3858,0.1212,0.0598,0.1385,0.0622,0.0465,0.1089,0.0073,0.7719,0.9888,0.4725
Celiac,0.3697,0.5470,0.0084,0.3827,0.5719,0.0475,0.4131,0.6010,0.0390,0.3987,0.5800,0.0211,0.3564,0.5430,0.0478,0.6844,0.9033,0.3305
Lupus,0.1466,0.2373,0.0075,0.2187,0.3757,0.1322,0.1557,0.2587,0.0145,0.1587,0.2545,0.0170,0.1472,0.2413,0.0106,0.3375,0.5038,0.1225
Acute MI,0.0889,0.1734,0.0772,0.1238,0.2643,0.1907,0.2173,0.3916,0.2813,0.0342,0.0907,0.0423,0.0266,0.0705,0.0045,0.6935,0.8993,0.4020

In [19]:
df34

,test/cls/Brier,test/cls/NLL,test/cal/aECE,test/cls/Brier,test/cls/NLL,test/cal/aECE
guo_los,0.3418,0.5205,0.0827,0.3217,0.5942,0.0995
guo_readmission,0.2431,0.4142,0.1125,0.2133,0.4799,0.0725
guo_icu,0.1508,0.2954,0.1702,0.0726,0.2176,0.0273
new_hypertension,0.2669,0.4497,0.0979,0.2417,0.4662,0.0677
new_hyperlipidemia,0.2722,0.4683,0.1059,0.2474,0.5244,0.0727
new_pancan,0.1403,0.2811,0.1914,0.0450,0.1058,0.0155
new_celiac,0.1190,0.2573,0.1981,0.0205,0.0660,0.0146
new_lupus,0.1281,0.2682,0.1975,0.0241,0.0685,0.0230
new_acutemi,0.2129,0.3695,0.1335,0.1282,0.2800,0.0393
lab_thrombocytopenia,0.3373,0.5223,0.0654,0.2964,0.4690,0.0355
lab_hyperkalemia,0.1383,0.2819,0.1829,0.0465,0.1089,0.0073
lab_hyponatremia,0.3827,0.5719,0.0475,0.3564,0.5430,0.0478
lab_anemia,0.2187,0.3757,0.1322,0.1472,0.2413,0.0106
lab_hypoglycemia,0.1238,0.2643,0.1907,0.0266,0.0705,0.0045

In [20]:
with open('results_single_mc_dropout.json') as f:
    results2 = json.load(f)

In [21]:
df2

                      test/cls/Brier  test/cls/NLL  test/cal/aECE
guo_los                       0.3092        0.4668         0.0294
guo_readmission               0.2057        0.3369         0.0220
guo_icu                       0.0717        0.1369         0.0186
new_hypertension              0.3744        0.5534         0.0394
new_hyperlipidemia            0.3607        0.5404         0.0317
new_pancan                    0.1465        0.2659         0.0917
new_celiac                    0.0645        0.1552         0.1078
new_lupus                     0.0983        0.2067         0.1314
new_acutemi                   0.2365        0.3857         0.0868
lab_thrombocytopenia          0.3322        0.5010         0.0363
lab_hyperkalemia              0.0598        0.1385         0.0622
lab_hyponatremia              0.3987        0.5800         0.0211
lab_anemia                    0.1587        0.2545         0.0170
lab_hypoglycemia              0.0342        0.0907         0.0423

In [41]:
# with open('results_single_bnn.json') as f:
#     results3 = json.load(f)

In [51]:
with open('results_model_uq_v3/results_single_task_baseline.json') as f:
    results11 = json.load(f)

with open('results_model_uq_v3/results_single_task_deep_ensemble.json') as f:
    results12 = json.load(f)

with open('results_model_uq_v3/results_single_task_mc_dropout.json') as f:
    results13 = json.load(f)

In [52]:
with open('results_model_uq_v3/results_multi_task_baseline.json') as f:
    results21 = json.load(f)
    
with open('results_model_uq_v3/results_multi_task_deep_ensemble.json') as f:
    results22 = json.load(f)
    
with open('results_model_uq_v3/results_multi_task_mc_dropout.json') as f:
    results23 = json.load(f)

In [53]:
df11 = read_results(results11)
df12 = read_results(results12)

df21 = read_results(results21)
df22 = read_results(results22)

df13 = read_results(results13)
df23 = read_results(results23)

In [54]:
df_single = pd.concat([df11, df12, df13], axis = 1)
df_single

                          test/cls/Brier  test/cls/Brier  test/cls/Brier
value_los                         0.5135          0.5031          0.5246
value_icu                         0.5073          0.5038          0.4904
value_hypoglycemia                0.5000          0.5088          0.5010
value_hyperkalemia                0.5000          0.4916          0.4995
value_hyponatremia                0.5014          0.5022          0.5029
value_anemia                      0.5150          0.5159          0.5058
value_thrombocytopenia            0.4955          0.4985          0.4992
value_new_hypertension            0.5314          0.5316          0.5219
value_new_hyperlipidemia          0.5543          0.5491          0.5579
value_new_acutemi                 0.6563          0.6382          0.6347

In [55]:
df_multiple = pd.concat([df21, df22, df23], axis=1)
df_multiple

                          test/cls/Brier  test/cls/Brier  test/cls/Brier
value_los                         0.5030          0.5060          0.5207
value_icu                         0.4898          0.4826          0.5140
value_hypoglycemia                0.4856          0.4898          0.4850
value_hyperkalemia                0.4841          0.5116          0.4938
value_hyponatremia                0.5009          0.4931          0.4979
value_anemia                      0.5106          0.5219          0.5156
value_thrombocytopenia            0.5059          0.5003          0.5031
value_new_hypertension            0.5520          0.5426          0.5427
value_new_hyperlipidemia          0.5640          0.5580          0.5410
value_new_acutemi                 0.6121          0.6079          0.5923