In [55]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import time
import seaborn as sns
import numpy as np
from sklearn.metrics import roc_curve, auc, roc_auc_score
import matplotlib.pyplot as plt

In [56]:
df1 = pd.read_csv('df_general_results.csv')
df1 = df1.loc[[0, 1]]
df2 = pd.read_csv('df_lab_results.csv')
df3 = pd.read_csv('df_diag_results.csv')

In [57]:
df_all = pd.concat([df1, df2, df3])

In [58]:
df_all

,0,1,0.1,1.1,0.2,1.2,0.3,1.3,0.4,1.4,0.5,1.5
0,0.5430,0.4570,0.6153,0.4265,0.3614,0.4992,0.5125,0.4875,0.5461,0.8385,0.6166,0.7237
1,0.5047,0.5331,0.6853,0.3596,0.5938,0.5140,0.7083,0.4888,0.5538,0.6455,0.7552,0.4831
0,0.5327,0.4460,0.3745,0.5464,0.2917,0.5548,0.2062,0.5246,0.3235,0.6382,0.2973,0.5594
1,0.4795,0.4821,0.3673,0.5988,0.2508,0.5094,0.4020,0.5125,0.2553,0.8470,0.3446,0.5948
2,0.5404,0.4410,0.5416,0.4352,0.7131,0.4388,0.6688,0.4481,0.7052,0.5274,0.6386,0.5723
3,0.4593,0.5220,0.3189,0.6303,0.2652,0.5347,0.2844,0.4939,0.2745,0.6186,0.2437,0.6786
4,0.4433,0.6100,0.2739,0.7254,0.1962,0.6877,0.2173,0.6044,0.2037,0.7722,0.2069,0.6825
0,0.4762,0.5238,0.5758,0.4707,0.7136,0.4488,0.7136,0.4222,0.6920,0.5606,0.7042,0.6804
1,0.5559,0.4203,0.5478,0.5032,0.6289,0.4077,0.6845,0.4127,0.7109,0.4014,0.6736,0.7338
2,0.5455,0.4545,0.4929,0.6379,0.7317,0.3394,0.6149,0.3436,0.6403,0.6053,0.6074,0.7335

In [66]:
def df_to_latex(df):
    latex_str = ""
    for index, row in df.iterrows():
        # Create a string for each row
        row_str = ""
        for i, val in enumerate(row):
            if index == 0 and i == 1:  # Condition to color the second cell of the first row
                row_str += f"\\cellcolor{{red}}{val:.4f} & "
            else:
                row_str += f"{val:.4f} & "
        row_str = '&' + row_str.strip('& ') + " \\\\\n"  # Remove the last '&'
        latex_str += row_str
    return latex_str


def format_latex_with_color(df):
    latex_str = ""
    for index, row in df.iterrows():
        # Separate odd and even indexed columns and find max for each category
        odd_max = row.iloc[::2].max()  # max for odd columns in the current row
        even_max = row.iloc[1::2].max()  # max for even columns in the current row

        row_str = "& "
        for i, value in enumerate(row):
            # Check if current column is odd or even
            if i % 2 == 0:  # Odd column index
                # Apply color if this value is the max in the odd columns
                if value == odd_max:
                    row_str += f"\\cellcolor{{gray!12}}{value:.4f} & "
                else:
                    row_str += f"{value:.4f} & "
            else:  # Even column index
                # Apply color if this value is the max in the even columns
                if value == even_max:
                    row_str += f"\\cellcolor{{gray!12}}{value:.4f} & "
                else:
                    row_str += f"{value:.4f} & "

        # Remove the last '&' and add a LaTeX new line command
        row_str = row_str.strip('& ') + " \\\\\n"
        latex_str += "& "+row_str

    return latex_str

def format_latex_with_color_v2(df):
    latex_str = ""
    for index, row in df.iterrows():
        # Separate odd and even indexed columns and find max for each category
        odd_max = row.iloc[::2].max()  # max for odd columns in the current row
        even_max = row.iloc[1::2].max()  # max for even columns in the current row

        row_str = "& "
        for i, value in enumerate(row):
            print(i)
            # Check if current column is odd or even
            if i % 2 == 0:  # Odd column index
                # Apply color if this value is the max in the odd columns
                if value == odd_max:
                    row_str += f"\\cellcolor{{gray!12}}{value:.4f} & "
                else:
                    row_str += f"{value:.4f} & "
            else:  # Even column index
                # Apply color if this value is the max in the even columns
                if value == even_max:
                    row_str += f"\\cellcolor{{gray!12}}{value:.4f} & "
                else:
                    row_str += f"{value:.4f} & "

        # Remove the last '&' and add a LaTeX new line command
        row_str = row_str.strip('& ') + " \\\\\n"
        latex_str += "& "+row_str

    return latex_str

In [68]:
a = format_latex_with_color_v2(df_all)
print(a)

0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
& 0.5430 & 0.4570 & 0.6153 & 0.4265 & 0.3614 & 0.4992 & 0.5125 & 0.4875 & 0.5461 & \cellcolor{gray!12}0.8385 & \cellcolor{gray!12}0.6166 & 0.7237 \\
& 0.5047 & 0.5331 & 0.6853 & 0.3596 & 0.5938 & 0.5140 & 0.7083 & 0.4888 & 0.5538 & \cellcolor{gray!12}0.6455 & \cellcolor{gray!12}0.7552 & 0.4831 \\
& \cellcolor{gray!12}0.5327 & 0.4460 & 0.3745 & 0.5464 & 0.2917 & 0.5548 & 0.2062 & 0.5246 & 0.3235 & \cellcolor{gray!12}0.6382 & 0.2973 & 0.5594 \\
& \cellcolor{gray!12}0.4795 & 0.4821 & 0.3673 & 0.5988 & 0.2508 & 0.5094 & 0.4020 & 0.5125 & 0.2553 & \cellcolor{gray!12}0.8470 & 0.3446 & 0.5948 \\
& 0.5404 & 0.4410 & 0.5416 & 0.4352 & \cellcolor{gray!12}0.7131 & 0.4388 & 0.6688 & 0.4481 & 0.7052 & 0.5274 & 0.6386 & \cellcolor{gray!12}0.5723 \\
& \cellcolor{gray!12}0.4593 & 0.5220 & 0.3189 & 0.6303 & 0.2652 & 0.5347 & 0.2844 & 0.4939 & 0.2745 & 0.6186 & 0.2437 & \cellcolor{gray!12}0.6786 \\
& \cellcolor{gray!12}0.4433 & 0.6100 & 0.2739 & 0.7254 & 0.1962 & 0.6877 & 0.2173 & 0.6044 & 0.2037 & \cellcolor{gray!12}0.7722 & 0.2069 & 0.6825 \\
& 0.4762 & 0.5238 & 0.5758 & 0.4707 & \cellcolor{gray!12}0.7136 & 0.4488 & \cellcolor{gray!12}0.7136 & 0.4222 & 0.6920 & 0.5606 & 0.7042 & \cellcolor{gray!12}0.6804 \\
& 0.5559 & 0.4203 & 0.5478 & 0.5032 & 0.6289 & 0.4077 & 0.6845 & 0.4127 & \cellcolor{gray!12}0.7109 & 0.4014 & 0.6736 & \cellcolor{gray!12}0.7338 \\
& 0.5455 & 0.4545 & 0.4929 & 0.6379 & \cellcolor{gray!12}0.7317 & 0.3394 & 0.6149 & 0.3436 & 0.6403 & 0.6053 & 0.6074 & \cellcolor{gray!12}0.7335 \\